version: '3'

services:
  fxDB:
    image: postgres
    volumes:
      - "/home/pi/GitRepo/DockerData/fxDB:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=abcd1234"

  pgAdmin:
    image: naobana/pgadmin4:latest
    volumes:
      - "/home/pi/GitRepo/DockerData/pgAdmin:/pgadmin"
    ports:
      - "5050:5050"
    
  FXDataCollector:
    build: ./FXDataCollector
    image: sulatnijag/fxdatacollector:latest
    stdin_open: true
    tty: true
    volumes: 
      - "/home/pi/GitRepo/Algo/FXDataCollector:/usr/src/app/FXDataCollector"


  
